#cloud-config
autoinstall:
  version: 1

  interactive-sections: []
    # - network
    # - identity

  locale: en_US.UTF-8
  keyboard:
    layout: us

  timezone: Europe/London

  # network:
  #   version: 2
  #   ethernets:
  #     enp0s3:  # or use match driver/name more carefully
  #       dhcp4: true
  #       dhcp-identifier: mac


  source:
    id: ubuntu-server

  identity:
    hostname: replace_me_hostname
    username: replace_me_username
    password: replace_me_password

  ssh:
    install-server: true
    allow-pw: true
    authorized-keys: []

  apt:
    preserve_sources_list: false
    mirror-selection:
      primary:
        - country-mirror
        - uri: "http://archive.ubuntu.com/ubuntu"
          arches: [i386, amd64]
        - uri: "http://ports.ubuntu.com/ubuntu-ports"
          arches: [s390x, arm64, armhf, powerpc, ppc64el, riscv64]
    fallback: abort
    geoip: true

  updates: security

  storage:
    layout:
      name: lvm
      match:
        size: largest
    swap:
      size: 0

  packages:
    - curl
    - tar
    # - unzip
    # - git

  # early-commands:

  late-commands:
    - cp /cdrom/postinstall/provision.sh /target/root/provision.sh
    - cp /cdrom/postinstall/postinstall.service /target/etc/systemd/system/postinstall.service
    - curtin in-target -- chmod +x /root/provision.sh
    - curtin in-target -- systemctl enable postinstall.service
  
  shutdown: poweroff
